spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paperflow
    driverClassName: org.postgresql.Driver
    username: paperflow_user
    password: paperflow123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
paperflow:
  fastapi-base-url: ${FASTAPI_BASE_URL:http://localhost:8001}